### ISSUE TITLE
can't finish the step  of "taxonkit create-dump"

### ISSUE THREAD

**Issue by lonestarling** [apcamargo/ictv-mmseqs2-protein-database#1] opened 2022-06-09 07:13 UTC
Apcamargo
Hi, 
A excellent tools for virus taxonomy, i just try your script ,but i meet a trouble about the 
taxonkit create-taxdump -K 1 -P 3 -C 5 -O 7 -F 9 -G 11 -S 13 -T 15 \
    --rank-names "realm","kingdom","phylum","class","order","family","genus","species" \
    ictv.taxonomy.tsv --out-dir ictv-taxdump

./fix_taxdump.py

i meet the error "Error: unknown shorthand flag: 'K' in -K"
shoul i change the command to " taxonkit reformat -f"?, how can i solve it, sir?

Best wishes
Lonestarling

**Comment by apcamargo** [comment] 2022-06-09 12:24
This was probably caused by some changes in the latest version of taxonkit. Try to run it with version [0.11.1](https://github.com/shenwei356/taxonkit/releases/tag/v0.11.1). I'll update the guide to work with version 0.12.0 in the future.

**Comment by lonestarling** [comment] 2022-06-10 01:35
@apcamargo 
Thank you so much, sir, I will try it again.

**Comment by lonestarling** [comment] 2022-06-11 14:28
Apcamargo 
Hi
i am here again, first of all, i refer the step of mmseqs taxonomy and your script, i finally get my virus sequence annotation. but i have another question about the inputfile,     i tried two options, the one is The nucleic acid sequence of the virus contig, and another  is amino sequence of the virus, both of them were by mmseqs easy-taonomy.  So what do I choose the two different results?
General speaking, the information about annotation were generated by protein sequence blast usually. 
so can you give me some advice? appreciated it 
L

**Comment by lonestarling** [comment] 2022-06-11 14:53
oh！ i get the illustration in mmseq user gude，Apcamargo

“For nucleotide-protein searches (contig taxonomy assignment) the final output is generated by the
aggregatetax module, and therefore more context is provided:”

thank you so much 
best wishes
L

**Comment by apcamargo** [comment] 2022-06-12 00:05
Good to know that everything worked out, @lonestarling. I'll close this issue for now

**Closed by apcamargo** 2022-06-12 00:05 UTC
